#Set your discord webhook url here!
#This is required for the plugin to function
webhook-url: "" #Enter webhook URL here!

#Toggle if the announcement should show!
announcements:
  ban: true
  mute: true
  warn: true
  kick: true
  unmute: true
  unban: true
  unwarn: true

#Commands: 'bhook reload' to reload the plugin
#Permissions: 'bhook.reload' is needed to reload the plugin